spring:

  h2:
    console:
      enabled: true
      path : /h2-console


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EasyCarPoolService?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: iridescent


jwt:
  header: Authorization
  #HS512
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 60000

logging:
  level:
    me.silvernine: DEBUG


val:
  adminsdk : "easycarpoolapp"

